   name: Daily Release

   on:
      schedule:
      - cron: "15 18 * * *"   # <=== Change this value
      workflow_dispatch:
       inputs:
         random:
           description: 'select whatever'
           required: false
           default: 'info'
           type: choice
           options:
           - info
           - warning
           - debug
   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Date
        run: |
           echo "time=$(date + "%Y-%m-%d")" >> $GITHUB_ENV
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Daily build ${{ env.TIME }}
          tag: nightly-${{ env.TIME }}
