   name: Daily Release

   on:
      schedule:
      - cron: "15 18,6 * * *"   # <=== Change this value
      workflow_dispatch:
       inputs:
         random:
           description: 'select whatever'
           required: false
           default: 'info'
           type: choice
           options:
           - info
           - warning
           - debug
   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Get Date
        run: |
           echo "time=$(date + "%Y-%m-%d")" >> $GITHUB_ENV
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: nightly-${{ github.time }}
          release_name: Nightly build ${{ github.time }}
          body: |
            Daily build of Ben-C.
          draft: false
          prerelease: false
