   name: Nightly Release

   on:
      schedule:
      - cron: "00 17 * * *"   # <=== Change this value
      workflow_dispatch:
       inputs:
         random:
           description: 'select whatever'
           required: false
           default: 'info'
           type: choice
           options:
           - info
           - warning
           - debug
   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: nightly-${{ env.RELEASE_DATE }}
          tag: nightly-${{ env.RELEASE_DATE }}
